---
title: "Who benefits from industrial policy? Evidence from firm investment grants (with Manuel Rosa Cruz)"
collection: publications
category: research_project
permalink: /publication/industrial-policy-investment-grants
date: 2026-05-20




---

This paper studies the distributional consequences of firm investment grants. We exploit Portugal’s PT2020 program, a major component of the European Union’s Cohesion Policy, which allocates investment support through competitive calls for applications. Using administrative data covering the universe of applicants, we compare funded firms with unsuccessful applicants within the same call and complement the analysis with local comparisons around the effective funding cutoff. We find that investment grants generate substantial increases in capital accumulation, employment, value added, and profitability. Despite these large firm-level gains, we find little evidence of changes in workforce composition. Instead, the gains generated by investment support are distributed unevenly. Profitability increases substantially, while wage gains are concentrated among incumbent workers employed in high-skill occupations. By contrast, workers employed in non-high-skill occupations experience little wage growth. Finally, larger grants generate additional increases in firm scale and profitability but no corresponding wage gains for incumbent workers. This contrast indicates that the distribution of gains within firms does not scale proportionally with the magnitude of investment support. Overall, our findings indicate that industrial policy generates substantial economic gains, but that these gains accrue disproportionately to firm owners and skilled workers.
